default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: <GCP_PROJECT_NAME>
      dataset: dbt
      location: US
      threads: 2
      keyfile: /credentials-dev/dev.json
    prod:
      type: bigquery
      method: service-account
      project: <GCP_PROJECT_NAME>
      dataset: dbt
      location: US
      threads: 2
      keyfile: /credentials-prod/prod.json
